### ISSUE TITLE
Report | Using ₺ sign after the value

### ISSUE THREAD

**Issue by mertssmnoglu** [needim/giderim-pwa#1]
According to the turkish traditional currency formatting ₺(TRY) sign placed after the value. Current label shows "₺20", this situation is not that bad but it's against the local tradition.

I think you can fix this and similar issues with an international currency formatter library.

**Comment by needim** [comment]
Good point! But I'm using Inl.NumberFormat for supporting many more currencies and it behaves like this. Maybe we can reach to MDN.

They are showing symbol at first when locale is TR,
but showing at end when local is DE for example.

https://github.com/needim/giderim-pwa/blob/b16a14667cafb4c82d45be582d4891c996a7d3e7/src/lib/utils.tsx#L322-L329

**Comment by needim** [comment]
Can you provide more information for currency symbol placement on Turkish language?

**Comment by onursimsek** [comment]
I don't think this is wrong usage. it's not an abbreviation (TRY), it's a symbol (₺)

[source](https://tr.wikipedia.org/wiki/T%C3%BCrk_liras%C4%B1_simgesi#Kullan%C4%B1m%C4%B1)

**Comment by needim** [comment]
Looks like the placement is correct. I'm closing this issue but feel free to re-open.
